# Generated by Django 5.2.4 on 2025-08-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_inquiry_is_approved_alter_inquiry_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='title',
            field=models.CharField(default=1, max_length=455),
            preserve_default=False,
        ),
    ]
