# Generated by Django 4.2.27 on 2026-01-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0004_alter_inquiry_phone'),
        ('inquiry', '0004_alter_inquiry_phone_alter_inquiry_title'),
    ]

    operations = [
    ]
