# Generated by Django 4.2.27 on 2026-01-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0005_merge_20260114_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='title',
            field=models.CharField(default='', max_length=455),
            preserve_default=False,
        ),
    ]
