# Generated by Django 4.2.27 on 2026-01-14 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_alter_customuser_contact_person'),
        ('inquiry', '0006_alter_inquiry_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_inquiries', to='User.contactperson'),
        ),
    ]
