# Generated by Django 5.2.4 on 2025-07-29 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactassignment',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='contactassignment',
            name='contact_persons',
            field=models.ManyToManyField(limit_choices_to={'is_staff': True}, related_name='assigned_to_owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactassignment',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
