# Generated by Django 5.2.4 on 2025-07-31 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_delete_location_customuser_pucest_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
