# Generated by Django 5.2.4 on 2025-08-16 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_customuser_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='address',
            new_name='billing_location',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='pucest_locations',
            new_name='delivery_locations',
        ),
    ]
