# Generated by Django 5.2.4 on 2025-08-17 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_rename_address_customuser_billing_location_and_more'),
        ('location', '0005_remove_location_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='delivery_locations',
        ),
        migrations.AddField(
            model_name='customuser',
            name='assigned_locations',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='location.location'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='selected_location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_users', to='location.location'),
        ),
    ]
