# Generated by Django 5.2.4 on 2025-08-17 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_remove_customuser_delivery_locations_and_more'),
        ('location', '0005_remove_location_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='assigned_locations',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='selected_location',
        ),
        migrations.AddField(
            model_name='customuser',
            name='delivery_locations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.location'),
        ),
    ]
