# Generated by Django 5.2.4 on 2025-08-17 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_remove_customuser_assigned_locations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='delivery_locations',
            new_name='delivery_location',
        ),
    ]
