# Generated by Django 5.2.4 on 2025-08-18 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_rename_delivery_locations_customuser_delivery_location'),
        ('contacts', '0002_remove_contactassignment_contact_person_and_more'),
        ('location', '0005_remove_location_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_selected_contact_person', to='contacts.userselectedcontact'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='delivery_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_with_delivery_location', to='location.location'),
        ),
    ]
