# Generated by Django 5.2.4 on 2025-08-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_alter_customuser_options_customuser_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['created_at']},
        ),
    ]
