# Generated by Django 5.2.4 on 2025-11-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('new', 'New User'), ('active', 'Custom User'), ('inactive', 'Inactive')], default='new', max_length=10),
        ),
    ]
