# Generated by Django 5.2.4 on 2025-12-10 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_contactperson'),
        ('User', '0017_customuser_status'),
    ]

    operations = [
    ]
