# Generated by Django 4.2.27 on 2026-01-14 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_merge_0013_contactperson_0017_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_selected_contact_person', to='User.contactperson'),
        ),
    ]
