# Generated by Django 5.2.4 on 2025-08-19 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal', '0002_newsportal_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsportal',
            old_name='image',
            new_name='banner',
        ),
        migrations.AddField(
            model_name='newsportal',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='beton-news/pdfs/'),
        ),
    ]
