# Generated by Django 5.2.4 on 2025-08-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal', '0003_rename_image_newsportal_banner_newsportal_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsportal',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
