# Generated by Django 5.2.4 on 2025-12-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal', '0004_alter_newsportal_external_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsportal',
            name='pdf_file',
            field=models.FileField(default=1, upload_to='beton-news/pdfs/'),
            preserve_default=False,
        ),
    ]
