<<<<<<< HEAD
# Generated by Django 5.2.4 on 2025-12-10 04:33
=======
# Generated by Django 5.2.4 on 2025-08-28 16:56
>>>>>>> bf5341a48f2fbd6b3dea89633236a8544cdfa80a

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal', '0004_alter_newsportal_external_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsportal',
            name='pdf_file',
            field=models.FileField(default=1, upload_to='beton-news/pdfs/'),
            preserve_default=False,
        ),
    ]
