# Generated by Django 5.2.4 on 2025-07-30 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'PUCEST Locations'},
        ),
    ]
