# Generated by Django 5.2.4 on 2025-08-16 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': 'Delivery Locations'},
        ),
    ]
