# Generated by Django 5.2.4 on 2025-08-17 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_rename_name_location_area_location_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='area',
        ),
    ]
