# Generated by Django 5.2.4 on 2025-08-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_registrationrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationRequest',
        ),
    ]
